# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(536, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_diagram = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_diagram.setGeometry(QtCore.QRect(20, 270, 501, 61))
        self.graphicsView_diagram.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.graphicsView_diagram.setObjectName("graphicsView_diagram")
        self.checkBox_diagram = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_diagram.setGeometry(QtCore.QRect(20, 240, 91, 17))
        self.checkBox_diagram.setChecked(False)
        self.checkBox_diagram.setObjectName("checkBox_diagram")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 207, 217))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("color: rgb(0, 0, 97);")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.date_start = QtWidgets.QDateEdit(self.groupBox)
        self.date_start.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_start.sizePolicy().hasHeightForWidth())
        self.date_start.setSizePolicy(sizePolicy)
        self.date_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_start.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.date_start.setFrame(True)
        self.date_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 13), QtCore.QTime(0, 0, 0)))
        self.date_start.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.date_start.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.date_start.setMinimumDate(QtCore.QDate(1752, 9, 14))
        self.date_start.setCalendarPopup(True)
        self.date_start.setDate(QtCore.QDate(2017, 9, 13))
        self.date_start.setObjectName("date_start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.date_start)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.date_end = QtWidgets.QDateEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_end.sizePolicy().hasHeightForWidth())
        self.date_end.setSizePolicy(sizePolicy)
        self.date_end.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_end.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.date_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 13), QtCore.QTime(0, 0, 0)))
        self.date_end.setCalendarPopup(True)
        self.date_end.setDate(QtCore.QDate(2018, 9, 13))
        self.date_end.setObjectName("date_end")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.date_end)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.SpinBox_square = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_square.sizePolicy().hasHeightForWidth())
        self.SpinBox_square.setSizePolicy(sizePolicy)
        self.SpinBox_square.setMaximumSize(QtCore.QSize(87, 16777215))
        self.SpinBox_square.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpinBox_square.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.SpinBox_square.setAccelerated(True)
        self.SpinBox_square.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBox_square.setKeyboardTracking(False)
        self.SpinBox_square.setPrefix("")
        self.SpinBox_square.setMaximum(349.99)
        self.SpinBox_square.setProperty("value", 50.0)
        self.SpinBox_square.setObjectName("SpinBox_square")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SpinBox_square)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_price = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_price.sizePolicy().hasHeightForWidth())
        self.spinBox_price.setSizePolicy(sizePolicy)
        self.spinBox_price.setMaximumSize(QtCore.QSize(87, 16777215))
        self.spinBox_price.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_price.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.spinBox_price.setAccelerated(True)
        self.spinBox_price.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_price.setKeyboardTracking(False)
        self.spinBox_price.setMinimum(1)
        self.spinBox_price.setMaximum(40000)
        self.spinBox_price.setSingleStep(100)
        self.spinBox_price.setProperty("value", 10000)
        self.spinBox_price.setObjectName("spinBox_price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_price)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_prepayment = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_prepayment.sizePolicy().hasHeightForWidth())
        self.spinBox_prepayment.setSizePolicy(sizePolicy)
        self.spinBox_prepayment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_prepayment.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.spinBox_prepayment.setStyleSheet("gridline-color: rgb(0, 0, 143);")
        self.spinBox_prepayment.setAccelerated(True)
        self.spinBox_prepayment.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_prepayment.setKeyboardTracking(False)
        self.spinBox_prepayment.setPrefix("")
        self.spinBox_prepayment.setMinimum(0)
        self.spinBox_prepayment.setMaximum(1000000)
        self.spinBox_prepayment.setSingleStep(100)
        self.spinBox_prepayment.setProperty("value", 150000)
        self.spinBox_prepayment.setObjectName("spinBox_prepayment")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_prepayment)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 297, 217))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("color: rgb(0, 0, 97);")
        self.groupBox_2.setTitle("Calculation")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(-1, -1, 5, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_total = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_total.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_total.sizePolicy().hasHeightForWidth())
        self.spinBox_total.setSizePolicy(sizePolicy)
        self.spinBox_total.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_total.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_total.setWrapping(False)
        self.spinBox_total.setFrame(True)
        self.spinBox_total.setReadOnly(True)
        self.spinBox_total.setAccelerated(False)
        self.spinBox_total.setPrefix("")
        self.spinBox_total.setMinimum(200000)
        self.spinBox_total.setMaximum(2000000)
        self.spinBox_total.setSingleStep(10)
        self.spinBox_total.setProperty("value", 300000)
        self.spinBox_total.setObjectName("spinBox_total")
        self.gridLayout.addWidget(self.spinBox_total, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 2)
        self.spinBox_mon_pay = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_pay.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_pay.setSizePolicy(sizePolicy)
        self.spinBox_mon_pay.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_mon_pay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_pay.setWrapping(False)
        self.spinBox_mon_pay.setFrame(True)
        self.spinBox_mon_pay.setSpecialValueText("")
        self.spinBox_mon_pay.setAccelerated(True)
        self.spinBox_mon_pay.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_mon_pay.setKeyboardTracking(False)
        self.spinBox_mon_pay.setPrefix("")
        self.spinBox_mon_pay.setMinimum(1000)
        self.spinBox_mon_pay.setMaximum(2000000)
        self.spinBox_mon_pay.setSingleStep(100)
        self.spinBox_mon_pay.setProperty("value", 15000)
        self.spinBox_mon_pay.setObjectName("spinBox_mon_pay")
        self.gridLayout.addWidget(self.spinBox_mon_pay, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 2)
        self.spinBox_balance_amount = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_balance_amount.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_balance_amount.sizePolicy().hasHeightForWidth())
        self.spinBox_balance_amount.setSizePolicy(sizePolicy)
        self.spinBox_balance_amount.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_balance_amount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_balance_amount.setWrapping(True)
        self.spinBox_balance_amount.setFrame(True)
        self.spinBox_balance_amount.setReadOnly(True)
        self.spinBox_balance_amount.setAccelerated(False)
        self.spinBox_balance_amount.setPrefix("")
        self.spinBox_balance_amount.setMinimum(200000)
        self.spinBox_balance_amount.setMaximum(2000000)
        self.spinBox_balance_amount.setSingleStep(10)
        self.spinBox_balance_amount.setProperty("value", 200000)
        self.spinBox_balance_amount.setObjectName("spinBox_balance_amount")
        self.gridLayout.addWidget(self.spinBox_balance_amount, 3, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(0, 2))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 3, QtCore.Qt.AlignLeft)
        self.date_inflation = QtWidgets.QDateEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_inflation.sizePolicy().hasHeightForWidth())
        self.date_inflation.setSizePolicy(sizePolicy)
        self.date_inflation.setMinimumSize(QtCore.QSize(68, 0))
        self.date_inflation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_inflation.setCalendarPopup(True)
        self.date_inflation.setDate(QtCore.QDate(2017, 9, 13))
        self.date_inflation.setObjectName("date_inflation")
        self.gridLayout.addWidget(self.date_inflation, 7, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBox_mon_percent = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_percent.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_percent.setSizePolicy(sizePolicy)
        self.spinBox_mon_percent.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_mon_percent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_percent.setWrapping(True)
        self.spinBox_mon_percent.setFrame(True)
        self.spinBox_mon_percent.setAccelerated(False)
        self.spinBox_mon_percent.setPrefix("")
        self.spinBox_mon_percent.setMinimum(0)
        self.spinBox_mon_percent.setMaximum(200)
        self.spinBox_mon_percent.setSingleStep(1)
        self.spinBox_mon_percent.setProperty("value", 0)
        self.spinBox_mon_percent.setObjectName("spinBox_mon_percent")
        self.gridLayout.addWidget(self.spinBox_mon_percent, 7, 1, 1, 1)
        self.spinBox_mon_uah = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_uah.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_uah.setSizePolicy(sizePolicy)
        self.spinBox_mon_uah.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_mon_uah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_uah.setWrapping(True)
        self.spinBox_mon_uah.setFrame(True)
        self.spinBox_mon_uah.setReadOnly(False)
        self.spinBox_mon_uah.setAccelerated(False)
        self.spinBox_mon_uah.setPrefix("")
        self.spinBox_mon_uah.setMinimum(0)
        self.spinBox_mon_uah.setMaximum(50000)
        self.spinBox_mon_uah.setSingleStep(10)
        self.spinBox_mon_uah.setProperty("value", 0)
        self.spinBox_mon_uah.setObjectName("spinBox_mon_uah")
        self.gridLayout.addWidget(self.spinBox_mon_uah, 7, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 1, 1, 2)
        self.spinBox_total_percent = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_total_percent.sizePolicy().hasHeightForWidth())
        self.spinBox_total_percent.setSizePolicy(sizePolicy)
        self.spinBox_total_percent.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_total_percent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_total_percent.setWrapping(True)
        self.spinBox_total_percent.setFrame(True)
        self.spinBox_total_percent.setReadOnly(False)
        self.spinBox_total_percent.setAccelerated(False)
        self.spinBox_total_percent.setPrefix("")
        self.spinBox_total_percent.setMinimum(0)
        self.spinBox_total_percent.setMaximum(200)
        self.spinBox_total_percent.setSingleStep(1)
        self.spinBox_total_percent.setProperty("value", 0)
        self.spinBox_total_percent.setObjectName("spinBox_total_percent")
        self.gridLayout.addWidget(self.spinBox_total_percent, 9, 1, 1, 1)
        self.spinBox_total_uah = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_total_uah.sizePolicy().hasHeightForWidth())
        self.spinBox_total_uah.setSizePolicy(sizePolicy)
        self.spinBox_total_uah.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_total_uah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_total_uah.setWrapping(True)
        self.spinBox_total_uah.setFrame(True)
        self.spinBox_total_uah.setReadOnly(False)
        self.spinBox_total_uah.setAccelerated(False)
        self.spinBox_total_uah.setPrefix("")
        self.spinBox_total_uah.setMinimum(0)
        self.spinBox_total_uah.setMaximum(50000)
        self.spinBox_total_uah.setSingleStep(10)
        self.spinBox_total_uah.setProperty("value", 0)
        self.spinBox_total_uah.setObjectName("spinBox_total_uah")
        self.gridLayout.addWidget(self.spinBox_total_uah, 9, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.checkBox_include_inflation = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_include_inflation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_include_inflation.sizePolicy().hasHeightForWidth())
        self.checkBox_include_inflation.setSizePolicy(sizePolicy)
        self.checkBox_include_inflation.setMouseTracking(True)
        self.checkBox_include_inflation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_include_inflation.setChecked(True)
        self.checkBox_include_inflation.setTristate(False)
        self.checkBox_include_inflation.setObjectName("checkBox_include_inflation")
        self.gridLayout.addWidget(self.checkBox_include_inflation, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_diagram.setText(_translate("MainWindow", "Diagram view"))
        self.groupBox.setTitle(_translate("MainWindow", "Contract data"))
        self.label.setText(_translate("MainWindow", "Purchase date"))
        self.date_start.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_2.setText(_translate("MainWindow", "Completion date"))
        self.date_end.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_3.setText(_translate("MainWindow", "Apartment area"))
        self.SpinBox_square.setSuffix(_translate("MainWindow", " m2"))
        self.label_4.setText(_translate("MainWindow", "Price for one meter"))
        self.spinBox_price.setSuffix(_translate("MainWindow", " UAH"))
        self.label_5.setText(_translate("MainWindow", "Prepayment"))
        self.spinBox_prepayment.setSuffix(_translate("MainWindow", " UAH"))
        self.spinBox_total.setSuffix(_translate("MainWindow", " UAH"))
        self.label_8.setText(_translate("MainWindow", "Monthly payment"))
        self.spinBox_mon_pay.setSuffix(_translate("MainWindow", " UAH"))
        self.label_9.setText(_translate("MainWindow", "Balance amount"))
        self.spinBox_balance_amount.setSuffix(_translate("MainWindow", " UAH"))
        self.label_12.setText(_translate("MainWindow", "Additional monthly payment (current month by default)"))
        self.date_inflation.setDisplayFormat(_translate("MainWindow", "MM.yyyy"))
        self.spinBox_mon_percent.setSuffix(_translate("MainWindow", "%"))
        self.spinBox_mon_uah.setSuffix(_translate("MainWindow", " UAH"))
        self.label_11.setText(_translate("MainWindow", "Total payment of inflation"))
        self.spinBox_total_percent.setSuffix(_translate("MainWindow", "%"))
        self.spinBox_total_uah.setSuffix(_translate("MainWindow", " UAH"))
        self.label_6.setText(_translate("MainWindow", "Total "))
        self.checkBox_include_inflation.setText(_translate("MainWindow", "Include inflation index"))

